### ISSUE TITLE
Herelink HDMI1 video

### ISSUE THREAD

**Issue by DonLakeFlyer** [DonLakeFlyer/Herelink-QGC-Save#9]
RTSP URL   ---->   rtsp://192.168.0.10:8554/H264Video
Aspect ratio   1.777777
record file format   mkv

https://github.com/CubePilot/qgroundcontrol-herelink/blob/herelink-v4.0.8/src/VideoStreaming/VideoStreamControl.cc#L267

**Comment by julianoes** [comment]
Where did you find `H264Video`? For me it works with: `rtsp://192.168.43.1:8554/fpv_stream` which I got from the docs: https://docs.cubepilot.org/user-guides/herelink/herelink-user-guides/share-video-stream

But I suspect that's just the forwarded video.

Nevermind, you are correct.
